### PR TITLE
absinthe_plug is a dependency or distillery release breaks otherwise

### PR DESCRIPTION
**Pull request by stephenmoloney**
- Add absinthe_plug dependecy
- Update deps to latest.

### CODE REVIEW

**Comment by sikanhe** [comment]
@stephenmoloney Can you show me how does it break distillery? I haven't created an elixir release in a while. 

Edit: nvm saw the issue.

**Comment by sikanhe** [comment]
@stephenmoloney Do you mind testing out `optional: true`? I will merge the PR if it works!

**Comment by stephenmoloney** [comment]
yea, I'll do this at some point in next few days... cheers

**Comment by stephenmoloney** [comment]
i pushed this change to a new PR.. i had forgotten about this one....

i'll close this in favour of the other one...

https://github.com/sikanhe/apollo-tracing-elixir/pull/17

**Pull request closed without merging**
